### ISSUE TITLE
Champion's name revealed on thier lore

### ISSUE THREAD

**Issue by henrygame3** [nichtfurkan/LeagueLoreGuesser#1]
One of the Randomized Lore
Revealed Neeko Name right there
![bilde](https://user-images.githubusercontent.com/29360012/167790871-37563b59-b543-443d-8fe3-82e06e0a9c6f.png)

**Comment by henrygame3** [comment]
Here is few other Found
Jayce
![bilde](https://user-images.githubusercontent.com/29360012/167792242-605710d4-58e8-401b-9332-bfc07393741e.png)
Lillia
![bilde](https://user-images.githubusercontent.com/29360012/167792269-c0448959-8c25-47c1-9a0b-f9cac4de985b.png)

**Comment by henrygame3** [comment]
Kog'Maw
![bilde](https://user-images.githubusercontent.com/29360012/167792667-830a65bf-b88a-4251-83b1-6a906d78b60c.png)

**Comment by henrygame3** [comment]
Illaoi
![bilde](https://user-images.githubusercontent.com/29360012/167793009-615de590-daab-4372-a930-ce17a99eee5e.png)

**Comment by nichtfurkan** [comment]
Thanks for reporting this bug.
The issue should be fixed in **[Release 1.3](https://github.com/nichtfurkan/LeagueLoreGuesser/releases/tag/1.3)**.
**If not please create a new Issue or reopen this one.**
